name: Update Pool Defs

on:
  schedule:
    - cron: '30 */4 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Trigger workflow manually' 

jobs:
  update_pools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token:  ${{ secrets.GIT_CC }}
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update JSON files
      run: |
        python -m pip install --upgrade pip
        pip install urllib3 jsbeautifier 
        python update_pools.py
    - name: Commit to repo
      run: |
        git add .
        git config --global user.name 'cardano-community'
        git config --global user.email '${{ secrets.GIT_EMAIL }}'
        git commit -am "Scheduled update"
        git push
